"""add_enroll_from_price_to_services

Revision ID: 2689808e614d
Revises: b192704617c1
Create Date: 2026-03-31 12:56:07.590137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2689808e614d'
down_revision: Union[str, Sequence[str], None] = 'b192704617c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('enroll_from_price', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'enroll_from_price')
    # ### end Alembic commands ###
