"""add role to admin_users

Revision ID: 7d78ad85b6f7
Revises: 4adddb8da2a2
Create Date: 2026-01-04 21:26:17.298578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d78ad85b6f7'
down_revision: Union[str, Sequence[str], None] = '4adddb8da2a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('role', sa.String(), nullable=True))
     # 2. Backfill existing rows
    op.execute(
        "UPDATE admin_users SET role = 'admin' WHERE role IS NULL"
    )
    # 3. Enforce NOT NULL constraint
    op.alter_column(
        "admin_users",
        "role",
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_users', 'role')
    # ### end Alembic commands ###
